### ISSUE TITLE
feature request: Add flags to mark tests as graded and send notifications

### ISSUE THREAD

**Issue by x-zvf** [I-Al-Istannen/ilias-tests#4]
After grading, one still needs to manually select `Als bewertet markieren` and `Benachrichtigung senden` for each student, which is quite annoying.
It would be awesome if there were flags `--mark` and `--notify` to do this automatically.

These should either be standalone operations, or extra flags to `--upload-state`, I am not quite sure which would be the best.

**Comment by I-Al-Istannen** [comment]
The request you need to send to mark as done/notify includes *all answers*. So you either combine it with upload-state or you basically perform an on-the-fly download and then re-up it. I think putting it together with `upload-state` makes the most sense.

**Comment by I-Al-Istannen** [comment]
Also note that it will automatically be unmarked if you do not pass `--mark-done`, I do not extract that state before overwriting it. I think that is an acceptable behaviour though, you obviously weren't done if you change it :P
